runtime: nodejs18
env: standard

env_variables:
  DISCORD_TOKEN: ${DISCORD_TOKEN}
  SPORTSDEV_API_KEY: ${SPORTSDEV_API_KEY}
  KCORP_TEAM_ID: ${KCORP_TEAM_ID}
  CHECK_INTERVAL: "300000"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
  - url: /.*
    script: auto